name: Run Tests

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Test Execution
      run: mvn clean test "-Dkarate.options=--tags @all classpath:tests" -Dtest=KarateRunner
      
    - name: Execution result
      id: ex_res
      run: |
        if test -f "target/karate-reports"; then
            echo "karate-reports exists."
             
        else 
            echo "karate-reports not found"
        fi
            
    - name: Attach TestSuite
      uses: actions/upload-artifact@v2
      with:
        name: karate-reports
        path: "target/karate-reports"